name: test_example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  http: ^0.13.3
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  permission_handler: ^10.0.0
  font_awesome_flutter: ^10.1.0
  flutter_gemini: ^2.0.5
  lottie: ^2.7.0
  flutter_markdown: ^0.6.18+2
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
